DROP SEQUENCE MDBOARDSEQ;
DROP TABLE MDBOARD;

CREATE SEQUENCE MDBOARDSEQ;
--번호(SEQ), 작성자(WRITER), 제목(TITLE), 내용(CONTENT), 작성일(REGDATE)
CREATE TABLE MDBOARD(
	NO NUMBER PRIMARY KEY,
	WRITER VARCHAR2(1000) NOT NULL,
	TITLE VARCHAR2(2000) NOT NULL,
	CONTENT VARCHAR2(4000) NOT NULL,
	REGDATE DATE NOT NULL
);

INSERT INTO MDBOARD VALUES(MDBOARDSEQ.NEXTVAL, '관리자', 'TEST 글', 'TEST 내용', SYSDATE);

SELECT NO, WRITER, TITLE, CONTENT, REGDATE FROM MDBOARD;

