/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.27
 * Generated at: 2021-01-08 01:37:34 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.my.dto.MyDto;
import java.util.List;
import com.my.dao.MyDao;

public final class mylist_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.my.dto.MyDto");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.my.dao.MyDao");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
 request.setCharacterEncoding("UTF-8"); 
      out.write(" <!-- 내가 요청 할 떄 저형식으로 요청 할꺼야 -->\r\n");
 response.setContentType("text/html;charset=UTF-8"); 
      out.write(" <!-- 내가 응답받는 문서의 형식은 html  -->\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("  ");
//다오랑 통신할껀데 다오에서 리스트에 디티오를 받아올꺼다.
  
  MyDao dao = new MyDao();
  
  List<MyDto> list = dao.selectList();
  
  
      out.write("\r\n");
      out.write("  \r\n");
      out.write("  <h1 align=\"center\">List</h1>\r\n");
      out.write("  \r\n");
      out.write("  <table border=\"1\" align=\"center\">\r\n");
      out.write("  \t<col width=\"50\">\r\n");
      out.write("  \t<col width=\"100\">\r\n");
      out.write("  \t<col width=\"200\">\r\n");
      out.write("  \t<col width=\"300\">\r\n");
      out.write("  \t\r\n");
      out.write("  \t<tr>\r\n");
      out.write("  \t\t<th>번호</th>\r\n");
      out.write("  \t\t<th>작성자</th>\r\n");
      out.write("  \t\t<th>제목</th>\r\n");
      out.write("  \t\t<th>작성일</th>\r\n");
      out.write("  \t</tr>\r\n");
      out.write("  \t\r\n");
      out.write("  \t\r\n");
 for(int i =0; i<list.size() ;i++)

{
      out.write("  \t\r\n");
      out.write("\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>");
      out.print(list.get(i).getMyno() );
      out.write("</td><!-- 값을 html에다가 넣어주세요 -->\r\n");
      out.write("\t\t\t<td>");
      out.print(list.get(i).getMyname() );
      out.write("</td>\r\n");
      out.write("\t\t\t<td><a href=\"mydetail.jsp?myno=");
      out.print(list.get(i).getMyno());
      out.write('"');
      out.write('>');
      out.print(list.get(i).getMytitle() );
      out.write("</a></td>\r\n");
      out.write("\t\t\t<td>");
      out.print(list.get(i).getMydate() );
      out.write("</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
 }
      out.write("\r\n");
      out.write("  \t<tr>\r\n");
      out.write("  \t\t<td colspan=\"4\" align=\"right\">\r\n");
      out.write("  \t\t\t<input type=\"button\" onclick=\"location.href='myinsert.jsp'\" value=\"글쓰기\">\r\n");
      out.write("  \t\t\t\r\n");
      out.write("  \t\t\t  <!-- ./는 생략가능 -->\r\n");
      out.write("  \t\t</td>\r\n");
      out.write("  \t</tr>\r\n");
      out.write("  \t\r\n");
      out.write("  \t\r\n");
      out.write("  </table>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
