DROP SEQUENCE MVCSEQ;

DROP TABLE MVCBOARD;

CREATE SEQUENCE MVCSEQ;

CREATE TABLE MVCBOARD(
SEQ NUMBER PRIMARY KEY,
WRITER VARCHAR2(500) NOT NULL,
TITLE VARCHAR2(1000) NOT NULL,
CONTENT VARCHAR2(4000) NOT NULL,
REGDATE DATE NOT NULL
);

INSERT INTO MVCBOARD VALUES(MVCSEQ.NEXTVAL,'관리자','TEST제목',
'TEST 내용',SYSDATE);

SELECT *FROM MVCBOARD ORDER BY SEQ DESC;

SELECT B.*
FROM (SELECT A.*, ROWNUM AS RNUM
FROM (SELECT * FROM PAGEBOARD ORDER BY SEQ DESC)A)B
WHERE RNUM BETWEEN 1 AND 10;
