DROP SEQUENCE CALBOARDSEQ;

DROP TABLE CALBOARD;

CREATE SEQUENCE CALBOARDSEQ;
--번호, 아이디, 제목, 내용, 일정, 작성일

CREATE TABLE CALBOARD(
SEQ NUMBER PRIMARY KEY,
ID VARCHAR2(1000) NOT NULL,
TITLE VARCHAR2(2000) NOT NULL,
CONTENT VARCHAR2(4000) NOT NULL,
MDATE VARCHAR2(12) NOT NULL,
REGDATE DATE NOT NULL);

SELECT * FROM CALBOARD;

--ROW_NUMBER() OVER(PARTITION BY @ ORDER BY)
--@로 GROUP BY해서 그룹별 ROWNUM사용 할 떄


SELECT * FROM(
   SELECT (ROW_NUMBER() OVER(PARTITION BY SUBSTR(MDATE,1,8) ORDER BY MDATE))RN,
   SEQ,ID,TITLE,CONTENT,MDATE,REGDATE
   FROM CALBOARD
   WHERE ID = 'kh' AND SUBSTR(MDATE,1,6)='202001'
)
WHERE RN BETWEEN 1 AND 3;

delete from calboard where seq = 1;


